<?php

$config = PhpCsFixer\Config::create()
    ->setRules(
        [
            '@Symfony' => true,
            'align_multiline_comment' => true,
            'array_syntax' => ['syntax' => 'short'],
            'linebreak_after_opening_tag' => true,
            // 'mb_str_functions' => true,
            // 'no_php4_constructor' => true,
            'no_superfluous_phpdoc_tags' => true,
            // 'no_unreachable_default_argument_value' => true,
            'no_useless_else' => true,
            'no_useless_return' => true,
            'ordered_imports' => true,
            // 'php_unit_strict' => true,
            'phpdoc_order' => true,
            'semicolon_after_instruction' => true,
            // 'strict_comparison' => true,
            // 'strict_param' => true,
        ]
    )
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__)
            ->exclude('assets')
            ->exclude('config')
            ->exclude('node_modules')
            ->exclude('public/bundles')
            ->exclude('public/build')
            ->exclude('translations')
            ->exclude('var')
            ->exclude('vendor')
            // exclude files generated by Symfony Flex recipes
            ->notPath('bin/console')
            ->notPath('public/index.php')
    );

return $config;
